### ISSUE TITLE
[REQ] \e\ and build (V)Machine

### ISSUE THREAD

**Issue by forart** [leiniercs/android_device_xiaomi_dandelion#1]
Hi there,
it would be great to have an [\e\ (aka deGoogled-Lineage)](https://e.foundation/) build for redmi 9* too.

Someone opened a request 3ad @ [\e\ community](https://community.e.foundation/) for these devices that we replied by linking your repo:

https://community.e.foundation/t/xiaomi-redmi-9-at/43802

If you need, here's a couple of interesting guides that may help to build it:
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Last but not least, we've also suggested (check [here](https://community.e.foundation/t/automated-builds-v-machine/43336)) to setup a "build (V)Machine" by modding these colab notebooks to made them device agnostic:
https://github.com/viam1-dev/colab_lineage_build
https://github.com/T110-android/colab_build

Hope can "inspire" you.

Thanks in advance.

**Comment by leiniercs** [comment]
Hello, thank you for reaching me out. I'm currently "trying" to create a device tree that is able of build an AOSP ROM with user build type (production build). I say "trying" because I'm struggling hard with the server part and that's the reason I haven't achieve my goal so far. I liked what /e/ is trying to achieve and it will be on the top list of my OASP ROMs to build.

**Comment by forart** [comment]
Hi there, thanks a lot for your fast reply !

We're glad to hear of your interest in \e\ and, if you need, feel free to ask for help inside their community.

As the above suggestion pushes, a Colab Notebook script should be taken is serious consideration even to let end users to "physically" see all build steps (and related instructions).

Thanks again for your work.
